server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PerfumeStore
    username: postgres
    password: tasneemgad
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    contexts: postgres
    change-log: classpath:/db/changelog/db.changelog-master.xml
  http:
    encoding:
      charset: UTF-8